### ISSUE TITLE
convertFromHtmlContent function crashes Application.

### ISSUE THREAD

**Issue by alptugyaman** [Afur/flutter_html_to_pdf#87]
Hello, I am using the 'flutter_html_to_pdf' package in the application I am working on. The application crashes due to the error I receive on the plugin side in the 'convertFromHtmlContent' function that I use when converting from HTML to PDF. Thanks for your help in advance.

<img width="1121" alt="Screenshot 2024-04-16 at 12 08 20" src="https://github.com/Afur/flutter_html_to_pdf/assets/13088809/497c7029-1772-4276-b2aa-7cd3c490fac0">

**Comment by Wahab-Khan** [comment]
I submitted a PR that:

Finds the host view controller in a scene-safe way (uses UIApplication.shared.connectedScenes on iOS 13+ and falls back to the legacy AppDelegate window for older apps).
Removes forced unwraps and returns a FlutterError instead of crashing if there’s no active root view controller yet.
Also relaxes the Dart SDK constraint so the package can be used with Dart 3 toolchains. 

I’ve opened a PR here: [PR](https://github.com/Afur/flutter_html_to_pdf/pull/98)
(If you can review/test it, that would be very helpful.)

Use my fix immediately (until PR is merged)
You can temporarily depend on my fork/branch in your pubspec.yaml:

```
dependencies:
  flutter_html_to_pdf:
    git:
      url: https://github.com/Wahab-Khan/flutter_html_to_pdf.git
      ref: ios-crash-issue-87
```
